version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: techplaza
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - DB_UPSTREAM= http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - "./server:/root/server:rw"
      - "./client/build:/root/client/build:ro"
    command: "npm run start:dev"