name: Docker

on:
  push:
    tags: ["v*.*.*"]

env:
  IMAGE_NAME_BACK: backend
  IMAGE_NAME_FRONT: frontend

jobs:
  backend_build:
    name: Build and push container image for back
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME_BACK }}:${{ steps.tag.outputs.tag }}

  frontend_build:
    name: Build and push container image for front
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME_FRONT }}:${{ steps.tag.outputs.tag }}
